### ISSUE TITLE
App crashes when beat is paused

### ISSUE THREAD

**Issue by Inverse3264** [thetwom/toc2#13]
I have downloaded version 1.6.7 from F-Droid and like it so far. The only problem I've experienced is that the app crashes whenever I pause the metronome. To reproduce:
1. Open the app
2. Leave it at default settings (one note, 120 BPM)
3. Press play
4. Press pause
The app will then crash.
I am using a Motorola G5 Plus running Android 8.1.0

**Comment by thetwom** [comment]
Thanks a lot for taking your time and reporting this bug. This should be solved in version [1.6.8](https://github.com/thetwom/toc2/releases/tag/v1.6.8), which hopefully is picked up by fdroid soon. Unfortunately, I didn't test enough before making 1.6.7 official. Sorry for the inconvenience.
Let me know if v1.6.8 doesn't solve it for you.
