### ISSUE TITLE
Keep screen on

### ISSUE THREAD

**Issue by DanBenHa** [thetwom/toc2#2]
Hi,

nice app! I have one feature request. Could you make the screen keep active while using the app?

Best wishes

**Comment by thetwom** [comment]
Thanks for the suggestion, will look into it. Sorry it took me so long to answer somehow github didn't notify me, that there were requests ...

**Comment by thetwom** [comment]
I added an option in the settings which allows to keep the screen on. Note, that this is not enabled by default.
