### ISSUE TITLE
Timing seems off

### ISSUE THREAD

**Issue by T-vK** [thetwom/toc2#3]
Hey, I just found your app on F-Droid and I really like the concept. But when I hit play, something is off. Especially the hi-hats don't seem consistent.
[sample.zip](https://github.com/thetwom/toc2/files/4241205/metronome.zip)
Maybe it would make sense to generate one long audio file and play that to avoid delays that come with looping and chaining audio files in real-time?

**Comment by thetwom** [comment]
thanks for the report, will took into it shortly. Sorry, for not answering before. Github didn't send me any mails, so I didn't know about it ...

**Comment by T-vK** [comment]
No problem, thanks for the reponse.

**Comment by thetwom** [comment]
just to get it right: What you mean is, that when mixing different sounds they are not perfectly on point? So e.g. hi-hat seems to play too early? Or do you mean that every now on then some sound is off?

**Comment by T-vK** [comment]
No it's actually even noticable with only hi-hats. The silence between each hi-hat is not consistent. Sometimes the delay between two hi-hats is a couple of milliseconds longer. And by sometimes I mean like every 3-7 beats, it's different every time.

**Comment by thetwom** [comment]
ok, thanks for the clarification. Seems that I have to stabilize the clock somehow. I will see what I can do.

**Comment by thetwom** [comment]
I tried to improve the timing, but unfortunately android brings no convenient functions to do this. And I guess its strongly dependent on the device. I will see if I can some up with some better idea in future, but maybe the newest version already brings some improvement. Would appreciate your feedback.

Will upload it to play store during the next days. fdroid should update automatically.

**Comment by T-vK** [comment]
Thanks, I'm using F-Droid. I'll report back when I get the update. 
Maybe have a look at the "Drum On!" source code. I'm not sure if it's 100% perfect, but it seems good enough for me: https://github.com/tube42/drumon

**Comment by T-vK** [comment]
I just got the update from F-Droid, unfortunetely I couldn't hear a difference. It's still not consistent. :/

**Comment by thetwom** [comment]
I feared that. However, I have a new core in the pipeline, which should really solve the problem! It will take some more time to get it integrated ...
Anyway, thanks for testing.

**Comment by T-vK** [comment]
That's great to hear. Thanks for your work.

**Comment by thetwom** [comment]
I did  a prerelease with the new player logic. Up to now it works flawless for me, but maybe you are willing to test it before I tag it as release such that it is captured by fdroid.
In case you are willing to test you find the apk under the 1.6.0-release ([link](https://github.com/thetwom/toc2/releases/download/v1.6.0-beta/metronome-1.6.0-beta.apk)). I would be interested if the metronome is accurate now, if the user interface is reactive and if there are any crashes.

**Comment by T-vK** [comment]
Just tested it and it sound pretty good. I can't hear any inconsistencies anymore.
The UI is responsive, reactive and I got not crashes.

Good job!

**Comment by thetwom** [comment]
That's great to hear. Thanks for your immediate testing and support! 

 I will also see how it performs on my mobile during the next days and then tag the release. In theory everything should by consistent now, but it's quite a big change, so I better give it some time.

**Comment by T-vK** [comment]
I agree. If I run into any issues with the test release I'll let you know.

**Comment by T-vK** [comment]
Found a bug. You can't tap in the tempo without getting a crash until you hit the play button at least once. This resets every time you restart the app.

**Comment by thetwom** [comment]
Thanks for the report. It seems as I already fixed this, since I can reproduce it with the 1.6.0 version but not with my latest developer version, where I basically cleaned up the code a bit. Will upload the new version soon.
