### ISSUE TITLE
Closing while playing breaks the App

### ISSUE THREAD

**Issue by bigboipete** [thetwom/toc2#36]
I found an issue in the 3.2.1-alpha:

1. Open app, start a beat
2. Close the app while playing
3. Reopen app
App opens showing the "Pause" button (instead of "Play"), no beat playing, no sound. Tapping "Pause" does nothing. Also on the scenes view you're stuck with the "Pause" button.

Expected behaviour would be, either continue playing with the same setting when closing the app or showing the "Play" button to again manually start playing.

**Comment by thetwom** [comment]
thanks for the info. Can indeed reproduce this. Will look into this when I find some time ...

**Comment by thetwom** [comment]
Should be fixed by latest version which is going to be released as v3.2.1.

**Comment by bigboipete** [comment]
Cool. This one is fixed in 3.2.1-alpha2. Works as expected now on my device.
