### ISSUE TITLE
Broken UI after 4.0.0

### ISSUE THREAD

**Issue by Long-FA** [thetwom/toc2#38]
I would like to report that Metronome UI is straight up broken in version 4.0.0 and 4.0.1. The play/pause ring is always on top, even after tapping the config button. The <<<<<<< button on top right also collides with BPM indicator. A screenshot should be self-explainatory.
![Metronome](https://user-images.githubusercontent.com/73825967/127221249-86f4d1e4-5acc-4e73-8d3d-4a7a7700f33f.png)

**Comment by thetwom** [comment]
Hi, sorry to hear that the UI is broken on your phone. I am not able to observe this here, so it might be a bit difficult to find a fix, at least for the problem that the play-pause-ring is always on top. However, here is a very quick first test. Can you check, if this fixes the problem? [v4.0.2-beta](https://github.com/thetwom/toc2/releases/tag/v4.0.2-beta)

For further looking into to problem and also to more easily improve the layout of the bpm-text, could you provide me your phone data? (exact phone model, android version, and if you have it available, the screen resolution)

**Comment by Long-FA** [comment]
Unfortunately 4.0.2 beta did not fix my issue. I'm running LineageOS 17.1 (Android 10) on Samsung Galaxy S8. The screen resolution should be 1440x2960px.
Here is a horizontal view, by the way
![Metronome](https://user-images.githubusercontent.com/73825967/127285219-bf87f020-ed06-4da2-86a0-089f12653fb0.png)

**Comment by thetwom** [comment]
Thanks, for providing the details. I will try to figure out a solution as soon as possible.

**Comment by thetwom** [comment]
I was able to reproduce your issue. Seemed to be a screen resolution issue which is very high for your phone. A little bit strange, that the beta didn't fix the issue. Maybe I failed to provide the latest file. Can you please check again with this version [v4.0.2-beta2](https://github.com/thetwom/toc2/releases/tag/v4.0.2-beta2). I also adjusted the settings of the bpm-text size so that it should not overlap with the scenes-button anymore. Still it is a bit crowded in this area ...

**Comment by Long-FA** [comment]
Thank you for the quick responsr. This new beta has indeed fixed the problem. I am closing this issue now. By the way i also feel the screen is a bit too crowded, you may want to scale everything down a bit.
>
>
>
>
> I was able to reproduce your issue. Seemed to be a screen resolution issue which is very high for your phone. A little bit strange, that the beta didn't fix the issue. Maybe I failed to provide the latest file. Can you please check again with this version > v4.0.2-beta2 <https://github.com/thetwom/toc2/releases/tag/v4.0.2-beta2>> . I also adjusted the settings of the bpm-text size so that it should not overlap with the scenes-button anymore. Still it is a bit crowded in this area ...
>
>

**Comment by thetwom** [comment]
Great to hear. Thanks again for taking the time and reporting the issue as well as testing! 

I think, I will release the current fixes short term, and then see if I can improve the layout further. It's hard to make it look good on so different aspect ratios ...
