### ISSUE TITLE
Current Version not available in F-Droid

### ISSUE THREAD

**Issue by Krawei** [thetwom/toc2#39]
Dear team,

when I take a look on google play store the current version is 4.0.1, in the F-Droid store the current version is 4.0.0.

What's the reason for this gap? Is there a bug in the build process?

Please fix this.

Kind Regards,

Krawei

**Comment by thetwom** [comment]
Hi, 

fdroid automatically picks up new versions from github, but it might take some days. It already found the latest version as you can see here at the bottom [metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.moekadu.metronome.yml) (there the version 4.0.1 is already mentioned). But compilation and providing it to the users takes some time, which is out of my control.
