### ISSUE TITLE
First Beat Sound continuosly Playing

### ISSUE THREAD

**Issue by kanaga-durga** [thetwom/toc2#4]
First Beat Sound 240 temp and 1 rythm sound playing continuosly ( Trick sound hearing).
Tempo Time different one and another beat

**Comment by kanaga-durga** [comment]
Please help me, we need to resolve these issues

**Comment by thetwom** [comment]
sorry, for not answering sooner, as stated elsewhere, github didn't mail me, so I didn't see your issue. Will look into it ...

**Comment by kanaga-durga** [comment]
Thanks for response, able to trigger issue

**Comment by thetwom** [comment]
Currently I am not sure, if this is the same issue as []( https://github.com/thetwom/toc2/issues/3)?
Maybe you could make a screenshot of your exact setting and show it here? 
What exactly do you mean by "Tempo Time different one and another beat"?

**Comment by kanaga-durga** [comment]
Hi 
I have shared the video file. In that 240 BPM, set one sound in bottom.
 you can clearly hear the sound different, First sound playing continuously this is happen first time.
1. Press pause and press play button few seconds issues is happen.
2. Press pause and press play button - it is working fine.

Please help me this scenario 

 


[20200415-183753-720x1280.zip](https://github.com/thetwom/toc2/files/4481365/20200415-183753-720x1280.zip)

**Comment by kanaga-durga** [comment]
I have shared the video file. In that 240 BPM, set one sound in bottom.
you can clearly hear the sound different, First sound playing continuously this is happen first time.

Press pause and press play button few seconds later - issues is happen.
Press pause and press play button immediately - it is working fine.

Please help me this scenario

[20200415-183753-720x1280.zip](https://github.com/thetwom/toc2/files/4481401/20200415-183753-720x1280.zip)

**Comment by thetwom** [comment]
Thanks, this made the problem very clear to me and I even reproduce it here. I fear this is a latency issue with the android-soundpool, but have to reassure, that this is the case.

In the end it seems as I don't get around rewriting the player to get rid of all time inaccuracies. Unfortunately this might take same time.

**Comment by kanaga-durga** [comment]
Thank you for your response, Is it possible to solve it, I have tried but not get resolve it

**Comment by thetwom** [comment]
I think there is a way for a quick fix (playing a mute sound to wake up the soundpool). Hopefully I shortly find some time to test this.

**Comment by kanaga-durga** [comment]
Thank you :)

**Comment by thetwom** [comment]
I added a fix and for me it seems to improve the situation. fdroid should pick up the new version hopefully soon, play store might also take some time ...
Please let me know if this works for you.

**Comment by kanaga-durga** [comment]
Thank you for your response, can you please let me know how long it will take new version will available in FDroid? 
How to identify new version is available in Frdroid?

**Comment by thetwom** [comment]
The version which has the fix is v1.5.1. fdroid shows me this version already.

**Comment by thetwom** [comment]
oh, I just realized, that it might show my local version. I guess we have to wait until fdroid updates ...

**Comment by kanaga-durga** [comment]
Fdroid shows  "Version 1.4.0 (11) suggested Added on 2020-01-10" version only, How long will take to update in Fdroid? any idea??

**Comment by thetwom** [comment]
fdroid at least realized that there is a version 1.5.0 ([](https://github.com/f-droid/fdroiddata/blob/master/metadata/de.moekadu.metronome.yml)). But it seems not to be built yet. I have no experience how long this will take. 
Version 1.5.1, which is has the fix is not even recognized yet.

**Comment by kanaga-durga** [comment]
Hi, Thank you for response, one more issue, We cannot find this issue in the application playing sound, Playing the application sound and record the sound in Audacity Software then only we can able to notice,first beat two sounds are playing silent (dung dung),
I have shared the files for your reference, Can you please check.

I don't know why it is happen
[Sample.zip](https://github.com/thetwom/toc2/files/4496195/Sample.zip)
.

**Comment by kanaga-durga** [comment]
Hi,
Every beat time interval must be same, Slight time difference happening. Please check this also, because every beat sound time interval is important.

![1](https://user-images.githubusercontent.com/51320617/79638646-3d393380-81a4-11ea-90bc-986297aecb35.png)
![2](https://user-images.githubusercontent.com/51320617/79638651-41fde780-81a4-11ea-92ad-122f354122e2.png)
![3](https://user-images.githubusercontent.com/51320617/79638652-43c7ab00-81a4-11ea-9a79-4e26260041da.png)
![4](https://user-images.githubusercontent.com/51320617/79638653-462a0500-81a4-11ea-8a9e-9e2e4b30c304.png)
![5](https://user-images.githubusercontent.com/51320617/79638668-593cd500-81a4-11ea-8950-a0d65fc99ded.png)

**Comment by thetwom** [comment]
Yes, the current way of how the timing is handled is not always accurate. I tried to improve the situation with version 1.5.0, but I fear it's not perfect yet.

Improving the situation needs a rewrite of the player. Rewriting this part takes some time and I do not know if I can manage this in the short term.

Regarding the two first bumps I would guess it is a problem with your setup and not an app issue? Maybe you want to test this with some other app in order to find out if its a general issue or it is a unique problem with the metronome app ...

**Comment by kanaga-durga** [comment]
Thank you for your response, If we play metronome app we not able to find this timing issue, My boss using this audacity software  for testing, that is bigger problem for me. 

Can you please tell me any technical reason for this issue for in android ?

Because this is  not happen in ios.

**Comment by thetwom** [comment]
The technical reason for the timing problem is that I currently rely on thread functionality. But there is no guarantee by android that the threads wake up in time. Additionally, there might be some latency for the sound starting to play, what seemed to be the cause for the first of your reported problems. I am trying to write a new player, which does not have all these problems, but this is no quick thing ...

Regarding your initial peaks in Audacity it seems that I currently can't help. Sorry :-(

**Comment by kanaga-durga** [comment]
Any way. Thank you so much for your respnse. If you get any solution please update.😊👍

**Comment by thetwom** [comment]
I did a prerelease with a new player logic which hopefully improves the accuracy of the metronome. I didn' t tag it as release so it won't appear on fdroid at the moment. But if you are willing to test, you find the apk at the 1.6.0 release ([link](https://github.com/thetwom/toc2/releases/download/v1.6.0-beta/metronome-1.6.0-beta.apk)). If you are willing to test, please share your opinion with me and if your issues are resolved. Or if there are any new problems ....

**Comment by kanaga-durga** [comment]
Thank you so much for your response, Let me check and let you know

**Comment by kanaga-durga** [comment]
Sorry for the delay, Thank you so much, I did not receive the comments from my team last one month, Just now got the response, They accept the Accuracy of the Metronome, 
Thank you so much for your support :)

**Comment by thetwom** [comment]
Thanks for the reply and your feedback to help improving the app.
