### ISSUE TITLE
Dear author

### ISSUE THREAD

**Issue by KingZD** [thetwom/toc2#41]
Hello, thank you very much for your open source code! I want to use the core code of your software in the project, hoping to get your authorization.

**Comment by thetwom** [comment]
Hi,
thanks for the honor of wanting to use some of my code. In principle, I have no problem, if the code is used somewhere else. Could you please give some more details about the software where you will use the code?

**Comment by KingZD** [comment]
> Hi,
> thanks for the honor of wanting to use some of my code. In principle, I have no problem, if the code is used somewhere else. Could you please give some more details about the software where you will use the code?

My app is a music application that allows users to use the metronome to find music rhythm. It is still in the development stage and is not available on Google play. If the application can be successfully completed, I will provide additional instructions later. Thank you for your open source code
