### ISSUE TITLE
ENHANCEMENT: More beat sound options

### ISSUE THREAD

**Issue by RabidAnubis** [thetwom/toc2#5]
Would be great if the app had the option to change the sound to a more conventional metronome click or user supplies their own sound.

**Comment by thetwom** [comment]
Thanks for the suggestion. Was thinking about user defined sounds, but this might be a bit tricky to get it running smoothly (without audio issues).
But maybe you have a suggestion about what kind of sound you would prefer. It appears quite difficult to find a good default sound, help is appreciated here.

**Comment by thetwom** [comment]
Closed this due to missing feedback. Please open a new report if there is still interest.
