### ISSUE TITLE
Android custom icon theming support

### ISSUE THREAD

**Issue by RustoMCSpit** [thetwom/toc2#71]

**Comment by thetwom** [comment]
You are talking about this? [adaptive icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)

**Comment by RustoMCSpit** [comment]
Yes, mainly the monochrome feature

**Comment by RustoMCSpit** [comment]
> You are talking about this? [adaptive icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)

the icon is bugged and only shows a solid yellow

**Comment by thetwom** [comment]
Thanks for the quick testing and report! Is now fixed in v4.9.1.

**Comment by RustoMCSpit** [comment]
close this issue
