### ISSUE TITLE
App crashes immediately in Android 14

### ISSUE THREAD

**Issue by natebragg** [thetwom/toc2#78]
I installed the app on Android 13, and it worked like a charm.  I upgraded to Android 14, and all the sudden it doesn't or at all.

**Comment by thetwom** [comment]
You are right, thanks for letting me know. I fixed the issues, will test it a bit and hopefully release by tomorrow. Then it depends on fdroid an google play how quickly it will be available there ...

**Comment by thetwom** [comment]
Ok, already released it. Here is the release: [v4.11.0](https://github.com/thetwom/toc2/releases/tag/v4.11.0), but as said, for fdroid and google play, it might take a few days ... hopefully everything works again.

**Comment by natebragg** [comment]
It works great!  Thanks for the quick turnaround.
