### ISSUE TITLE
How to change default sound?

### ISSUE THREAD

**Issue by axel-rank** [thetwom/toc2#9]
In your readme is described that you can choose different sounds.
But how? And where? There is no option in settings or somewhere else.
The default sound is not really usable.

**Comment by thetwom** [comment]
Just "click" on the note for which you want to choose a different sound. Or move the note upwards. Hopefully, one of the choices fits better for you.

Note, there is no option to have user defined sounds.

 Out of curiosity, what would be a preferred sound by you?

**Comment by tarikgraba** [comment]
I think there is an issue with the audio decoding on some devices. On my device (Lineage 14.1) the App is unusable, all the sounds are just noise.
I have even downloaded the resources from the repository to check if those were the intended sounds. The flaac files play correctly on my PC.

**Comment by thetwom** [comment]
> I think there is an issue with the audio decoding on some devices. On my device (Lineage 14.1) the App is unusable, all the sounds are just noise.
> I have even downloaded the resources from the repository to check if those were the intended sounds. The flaac files play correctly on my PC.

Thanks for the report. Lets discuss this in a separate issue. [link]{https://github.com/thetwom/toc2/issues/10}

**Comment by axel-rank** [comment]
Yes, exactly same issue on my Device (AEX/Lineage 7.1.2). Just noise, no matter what sound  I choose.

**Comment by thetwom** [comment]
thanks for the update. Since this is the same issue than [issue 10](https://github.com/thetwom/toc2/issues/10), I will close this now. Please have a look at this other issue. Maybe you can help by installing the DecoderTest as mentioned there:
> I actually updated the test ...maybe you could install the update, [DecoderTest v9.0]{[https://github.com/thetwom/DecoderTest/releases/tag/v9.0}](https://github.com/thetwom/DecoderTest/releases/tag/v9.0%7D), and start it. No pressing on "Decoded next track" needed anymore. Just post a screenshot of the app after it started.
